import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../core/api.service';import { apiError } from '../../core/api-error';import { User,UserCreate } from '../../core/models';
@Component({selector:'app-users',imports:[ReactiveFormsModule],template:`
<section class="page-header"><div><span class="eyebrow">Seguridad</span><h1>Gestión de usuarios</h1><p>Creá cuentas y asigná los roles disponibles del hospital.</p></div><button class="button primary" (click)="open.set(true)">+ Nuevo usuario</button></section>
<div class="info">El backend actual permite listar y crear usuarios. Todavía no posee endpoints para editar, bloquear o eliminar cuentas.</div>
@if(message()){<div class="success">{{message()}}</div>}@if(error()){<div class="alert">{{error()}}</div>}
<section class="panel list-panel">@if(loading()){<div class="loading">Cargando usuarios...</div>}@else{<div class="table-wrapper"><table><thead><tr><th>Usuario</th><th>Nombre</th><th>Correo</th><th>Roles</th><th>Estado</th></tr></thead><tbody>@for(u of users();track u.usuario_id){<tr><td><strong>{{u.nombre_usuario}}</strong></td><td>{{u.nombres}} {{u.apellidos}}</td><td>{{u.correo}}</td><td><div class="chips">@for(r of u.roles;track r){<span>{{r}}</span>}</div></td><td><span class="badge" [attr.data-status]="u.activo?'ACTIVO':'INACTIVO'">{{u.activo?'Activo':'Inactivo'}}</span></td></tr>}</tbody></table></div>}</section>
@if(open()){<div class="drawer-backdrop" (click)="close()"><aside class="drawer" (click)="$event.stopPropagation()"><div class="drawer-title"><div><span class="eyebrow">Cuenta nueva</span><h2>Registrar usuario</h2></div><button (click)="close()">×</button></div><form class="form-grid" [formGroup]="form" (ngSubmit)="save()"><label><span>Usuario *</span><input formControlName="nombre_usuario"></label><label><span>Contraseña *</span><input type="password" formControlName="password"></label><label><span>Nombres *</span><input formControlName="nombres"></label><label><span>Apellidos *</span><input formControlName="apellidos"></label><label class="full"><span>Correo *</span><input type="email" formControlName="correo"></label><div class="full roles"><strong>Roles *</strong>@for(role of roles;track role){<label><input type="checkbox" [checked]="selectedRoles().includes(role)" (change)="toggleRole(role)"><span>{{role}}</span></label>}</div><div class="actions full"><button type="button" class="button secondary" (click)="close()">Cancelar</button><button class="button primary" [disabled]="saving()">{{saving()?'Guardando...':'Crear usuario'}}</button></div></form></aside></div>}
`,styles:[`.info{margin-top:18px;padding:12px 14px;border:1px solid #b2ddff;border-radius:11px;color:#175cd3;background:#eff8ff;font-size:.7rem}.chips{display:flex;flex-wrap:wrap;gap:5px}.chips span{padding:4px 7px;border-radius:999px;color:#6941c6;background:#f2edff;font-size:.58rem;font-weight:800}.roles{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;padding:14px;border:1px solid var(--border);border-radius:12px}.roles>strong{grid-column:1/-1;font-size:.72rem}.roles label{display:flex;align-items:center;gap:7px;font-size:.67rem}.roles input{width:auto;min-height:auto}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class UsersComponent{private api=inject(ApiService);readonly users=signal<User[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly open=signal(false);readonly error=signal('');readonly message=signal('');readonly selectedRoles=signal<string[]>([]);readonly roles=['ADMINISTRADOR','RECEPCIONISTA','MEDICO','ENFERMERO','LABORATORIO','FARMACIA','CONTABILIDAD','PACIENTE','AUDITOR'];readonly form=new FormGroup({nombre_usuario:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(4)]}),password:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(8)]}),correo:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),nombres:new FormControl('',{nonNullable:true,validators:[Validators.required]}),apellidos:new FormControl('',{nonNullable:true,validators:[Validators.required]})});constructor(){this.load()}load(){this.loading.set(true);this.api.users().subscribe({next:v=>{this.users.set(v);this.loading.set(false)},error:e=>{this.error.set(apiError(e));this.loading.set(false)}})}toggleRole(r:string){this.selectedRoles.update(v=>v.includes(r)?v.filter(x=>x!==r):[...v,r])}save(){if(this.form.invalid||!this.selectedRoles().length||this.saving()){this.form.markAllAsTouched();this.error.set('Completá los campos y asigná al menos un rol.');return}this.saving.set(true);const v=this.form.getRawValue();const body:UserCreate={...v,roles:this.selectedRoles()};this.api.createUser(body).subscribe({next:()=>{this.saving.set(false);this.message.set('Usuario creado correctamente.');this.close();this.load()},error:e=>{this.saving.set(false);this.error.set(apiError(e))}})}close(){this.open.set(false);this.form.reset({nombre_usuario:'',password:'',correo:'',nombres:'',apellidos:''});this.selectedRoles.set([])}}
